blog/urls.py
from django.urls import path
from .views import (
     ArticelList ,
     ArticelDetail ,
     CategoryList ,
     AuthorList ,
     ArticelPreview,
     SearchList
)



app_name="blog"
urlpatterns=[
    path('',ArticelList.as_view(),name="home"),
    #path('main',mainposts,name="mainposts"),
    path('page/<int:page>',ArticelList.as_view(),name="home"),
    path('preview/<int:pk>',ArticelPreview.as_view(),name="preview"),
    path("posts/<slug:slug>/", ArticelDetail.as_view() , name="detail"),
    path("category/<slug:slug>/", CategoryList.as_view() , name="category"),
    path("category/<slug:slug>/page/<int:page>", CategoryList.as_view() , name="category"),
    path("author/<slug:username>/", AuthorList.as_view() , name="author"),
    path("author/<slug:username>/page/<int:page>", AuthorList.as_view() , name="author"),
    path("search/", SearchList.as_view() , name="search"),
    path("search/page/<int:page>", SearchList.as_view() , name="search1"),

    ]

firstsite/urls.py
from django.contrib import admin
from django.urls import path , include , re_path
from blog.views import  ArticelList
import blog.urls,account.urls
from account.views import Login , Register , activate
from payment.views import send_request ,verify

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(blog.urls)),
    path('',include('django.contrib.auth.urls')),
    path('login/', Login.as_view(), name='login'),
    path('register/',Register.as_view(), name='register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$',activate, name='activate'),
    path('account/',include(account.urls)),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('comment/', include('comment.urls')),
    path('request/', send_request, name='request'),
    path('verify/', verify , name='verify'),
    path('', include('social_django.urls', namespace='social')),
]
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.utils.html import format_html
from django.contrib.auth.models import User
from PIL import Image
from django.urls import reverse
from django.db.models.signals import post_save
from django.core.validators import MinLengthValidator
from account.models import User
from  .extentions.utils import jalali_converter
from django.contrib.contenttypes.fields import GenericRelation
from comment.models import Comment


# my manager

class ArticleAManager (models.Manager):
    def published(self):
        return self.filter(status='p')

class CategoryManager (models.Manager):
    def active(self):
        return self.filter(status=True)


class IpAddress(models.Model):
    ip_address = models.GenericIPAddressField(verbose_name="آدرس آی پی")


# Create your models here.

class Category (models.Model):
    parent= models.ForeignKey('self' , default=None ,null=True,blank=True,on_delete=models.SET_NULL, related_name="children", verbose_name="زیر مجموعه ")
    title= models.CharField(max_length=200, blank=True, verbose_name=" دسته بندی" )
    slug= models.SlugField (max_length=100, unique=True, null=False, blank=True, db_index=True , verbose_name="اسلاگ")
    status= models.BooleanField(default=True , verbose_name="آیا نمایش داده شود؟")
    position=models.IntegerField(verbose_name="موقعیت")



    class meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"
        ordering=["parent__id",'position']



    def __str__(self):
        return f"{self.title}"

    objects =CategoryManager()    



class Tag(models.Model):
    caption=models.CharField(max_length=20)

    def __str__ (self):
        return self.caption




class Authur(models.Model):
    name=models.CharField(max_length=50)
    family=models.CharField(max_length=50)
    email=models.EmailField(unique=True)

    def __str__(self):
        return f"{self.name} {self.family}"


 
class Article (models.Model):
    STATUS_CHOICES=[
    ("d","پیش نویس"),
    ("p","منتشر شده"),
    ("i"," در حال برسی"),
    ("b"," برگشت داده شده "),]
    
    author=models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, db_constraint=False, null=True, related_name="articel" , verbose_name="نویسنده")
    title= models.CharField(max_length=200, blank=True, verbose_name="عنوان مقاله")
    slug= models.SlugField (max_length=100, unique=True, null=False, blank=True, db_index=True , verbose_name="آدرس مقاله")
    category=models.ManyToManyField(Category , verbose_name="دسته بندی مقالات", related_name="articels")
    description = models.TextField(blank=True,validators=[MinLengthValidator(20)] , verbose_name="محتوا")
    thumbnail= models.ImageField(upload_to="images", blank=True , verbose_name="انتخاب تصویر")
    publish= models.DateTimeField(default=timezone.now , verbose_name="نشر")
    created= models.DateTimeField(auto_now_add=True)
    updated= models.DateTimeField(auto_now=True)
    status= models.CharField(max_length=1, choices=STATUS_CHOICES , verbose_name="وضعیت")
    is_special= models.BooleanField(default=False, verbose_name="کاربر ویژه")
    tags=models.ManyToManyField(Tag , verbose_name="#")
    comments = GenericRelation(Comment)
    hits= models.ManyToManyField(IpAddress , blank=True ,through="ArticleHit" , related_name="hits" , verbose_name="بازدید ها")
   



    class meta:
        verbose_name = "مقاله"
        verbose_name_plural = "مقالات"
        ordering=['-publish']
    

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return reverse('account:home')
        
    def jpublish(self):
        return jalali_converter(self.publish)
    jpublish.short_description="زمان انتشار"


    def thumbnail_tag(self):
        return format_html("<img  src='{}' width:40px height:75px>".format(self.thumbnail.url))

    def category_to_str (self):
        return ", ".join([category.title for category in self.category.active()])
    category_to_str.short_description="دسته بندی مقالات"
    pass
    

    objects = ArticleAManager()    


class ArticleHit(models.Model):

    article = models.ForeignKey(IpAddress ,on_delete= models.CASCADE)
    IpAddress = models.ForeignKey(Article ,on_delete= models.CASCADE)
    created= models.DateTimeField(auto_now_add=True)








# class Comment(models.Model):
#     title=models.CharField(max_length=200)
#     name=models.CharField(max_length=100)
#     email=models.EmailField(max_length=500)
#     text=models.TextField(max_length=500)
#     post=models.ForeignKey(Article,on_delete=models.CASCADE,blank=True)
#     user=models.ForeignKey(User, on_delete=models.CASCADE)
    
#     def __str__ (self):
#         return self.title

    

#class Profile(models.Model):

        #user = models.OneToOneField(auth.models.User, on_delete=models.CASCADE)
        #avatar = models.ImageField(default='1.jpg', upload_to='displays', height_field=None, width_field=None, max_length=None)
    

blog/views.py
from django.core.paginator import Paginator
from django.views.generic import ListView
from django.views.generic import DetailView
from django.shortcuts import render
# Create your views here.
from cgitb import html
from tkinter import N
from django.shortcuts import render , get_object_or_404 
from django.http import HttpResponse , JsonResponse
import datetime
from .models import Article , Category , ArticleHit
from django.contrib.auth.models import User
from account.mixins import AuthorAccessMixin
from django.db.models import Q

#def home(request , page=1):
    #article_list=Article.objects.published()
   # paginator = Paginator(article_list, 2)
    #category=Category.objects.all()
    #article = paginator.get_page(page)
    #context={
     #   "articels":article,
      #  "category":category,
      #  }
    #return render(request,"blog/home.html",context)

 
 # تغیر دهیم  articel_list.html را به   home.html   را بدهیم با باید  template_name = "blog/home.html"   اینجا یا باید اسم 


class ArticelList(ListView):
    queryset = Article.objects.published()
    paginate_by = 2
    #models=Articel
    #template_name = "blog/home.html"
    #context_object_name = "articels"


    

#def detail(request,slug):
  #  html=get_object_or_404(Article,slug=slug)
   # context={
    #    "article" :html
     #   }
    #return render (request,"blog/detail.html",context)


    
class ArticelDetail(DetailView):
    def get_object(self):
        slug=self.kwargs.get('slug')
        article=  get_object_or_404(Article.objects.published(),slug=slug)

        ip_address = self.request.user.ip_address
        if ip_address not in article.hits.all():
            article.hits.add(ip_address)

        return article
       

 



#برای پیش نمایش مقالات در سایت از قسمت اکانت
class ArticelPreview(AuthorAccessMixin,DetailView):
    def get_object(self):
        pk=self.kwargs.get('pk')
        return ( get_object_or_404(Article ,pk=pk))
 

#def category(request, slug , page=1):
    #category= get_object_or_404(Category, slug=slug , status=True)
    #article_list= category.articels.published()
    #paginator = Paginator(article_list, 2)
    #articels = paginator.get_page(page)
    #context={
     #   "category": category,
      #  "articels":articels,
       # }
    #return render (request,"blog/category.html",context)



class CategoryList(ListView):
    paginate_by = 2
    template_name= 'blog/category_list.html'

    def get_queryset(self):
        global category
        slug=self.kwargs.get('slug')
        category=  get_object_or_404(Category.objects.active(),slug=slug)
 
        return (category.articels.published())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Add in the publisher
        context['category'] = category
        return context


class AuthorList(ListView):
    paginate_by = 2
    template_name= 'blog/author_list.html'

    def get_queryset(self):
        global author
        username=self.kwargs.get('username')
        author=  get_object_or_404(User,username=username)
 
        return author.articel.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Add in the publisher
        context['author'] = author
        return context



class SearchList(ListView):
    paginate_by = 2
    template_name= 'blog/search_list.html'

    def get_queryset(self):
        search=self.request.GET.get('q')
        return Article.objects.filter(Q(description__icontains = search) | Q(title__icontains = search))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Add in the publisher
        context['search'] = self.request.GET.get('q')
        return context






    
 

comment/views/base.py
from django.views.generic import FormView

from comment.conf import settings
from comment.context import DABContext
from comment.responses import DABResponseData
from comment.messages import EmailInfo
from comment.service.email import DABEmailService
from comment.forms import CommentForm


class BaseCommentView(FormView, DABResponseData):
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = context.pop('form')
        context.update(DABContext(self.request))
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class CommentCreateMixin(BaseCommentView):
    email_service = None

    def _initialize_email_service(self, comment, request):
        self.email_service = DABEmailService(comment, request)

    def _send_notification_to_followers(self, comment, request):
        if settings.COMMENT_ALLOW_SUBSCRIPTION:
            self._initialize_email_service(comment, request)
            self.email_service.send_notification_to_followers()

    def perform_save(self, comment, request):
        comment.save()
        self._send_notification_to_followers(comment, request)
        comment.refresh_from_db()
        return comment

    def _handle_anonymous(self, comment, request, api=False):
        self._initialize_email_service(comment, request)
        self.email_service.send_confirmation_request(api=api)
        self.anonymous = True
        self.msg = EmailInfo.CONFIRMATION_SENT

    def perform_create(self, comment, request, api=False):
        if settings.COMMENT_ALLOW_ANONYMOUS and not comment.user:
            self._handle_anonymous(comment, request, api)
        else:
            comment = self.perform_save(comment, request)
        return comment

templates/blog/about.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>بلاگ من - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/about-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>About Me</h1>
                            <span class="subheading">This is what I do.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
                    </div>
                </div>
            </div>
        </main>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

templates/blog/article_detail.html
{% extends 'blog/base.html' %}
{% load comment_tags %} 
{% load ratings %} 
{% load comment_tags %}
{% load static %}
{% load base_tags %}
{% load humanize %}


{% block title %}
  {{article.title}}  
{% endblock %}

{% block main %}
<!-- Page Header-->
<header class="masthead" style="background-image: url('{{article.thumbnail.url}}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
               <h1>{{article.title}}</h1> 
               {% if article.is_special %}
               <span class="badge badge-danger" style="font-size: 14px; ">ویژه</span>
           
               {% endif %}
               <time>{{article.publish|naturaltime}}</time>
               <div>{% ratings article %}</div>
               <p style="text-align: right;" ></p><small>   آیا مطلب برای شما مفید بود؟</small></p>
               <div> بازدید ها : {{article.hits.count}}</div>
            </div>
        </div> 
    </div>
</div>
</header>

 <!-- Post Content-->
<article>
    <div class="container text-justify">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto ">
                {% popular_articles %}
                {% if object.is_special %}
                    {% if user.is_authenticated and user.is_special_user or user == object.auther or user.is_superuser %}
                        {{article.description|linebreaks|safe}}
                {% else %}
                    {{article.description|striptags|truncatewords:30}}
                    <p class="alert alert-warning">این مقاله ویژه است برای مشاهده آن باید<a class="alert-link" href="{% url 'request' %}"> اشتراک ویژه   </a>تهیه نمایید </p>
                {% endif %}

                {% else %}
                    {{article.description|linebreaks|safe}}
                {% endif %}


                {% render_comments object request %}  
                {% include_bootstrap %}

             </div>
        </div>
    </div>
  </article>

  {% endblock %}

templates/blog/article_list.html
{% extends 'blog/list.html' %}

{% block header %}{% endblock%}

{% block previous_page_url %}
{% url 'blog:home'  page_obj.previous_page_number %}
{% endblock %}


{% block next_page_url %}
{% url 'blog:home' page_obj.next_page_number %}
{% endblock %}

templates/blog/author_list.html
{% extends 'blog/list.html' %}


   {% block header %}
        <h3 class="alert alert-primary text-center">نویسنده:{{author.get_full_name}}</h3>
   {% endblock%}

   {% block previous_page_url %}
        {% url 'blog:author' author.username page_obj.previous_page_number %}
   {% endblock %}


   {% block next_page_url %}
        {% url 'blog:author' author.username page_obj.next_page_number %}
   {% endblock %}

templates/blog/base.html
{% load static%}
{% load base_tags %}



<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title> {% block title %} نوس{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'  rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static '/blog/css/styles.css'  %} rel="stylesheet" />
        <link href={% static '/blog/css/rtl.css'  %} rel="stylesheet" />

        <!--star rating static file-->
        <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
        <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>


        {% block custome-header%}

        {% endblock %}
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'blog:home' %}"> {% title %}</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                    {% category_navbar %}
                        </div>
                    </nav>
                            
            
                

        
        {% block main %}

        {% endblock %}
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'blog/js/scripts.js' %}"></script>
    </body>
</html>

templates/blog/category_list.html
{% extends 'blog/list.html' %}


   {% block header %}
        <h3 class="alert alert-primary text-center">{{category.title}}</h3>
   {% endblock%}

   {% block previous_page_url %}
        {% url 'blog:category' category.slug page_obj.previous_page_number %}
   {% endblock %}


   {% block next_page_url %}
        {% url 'blog:category' category.slug page_obj.next_page_number %}
   {% endblock %}

templates/blog/list.html
{% extends 'blog/base.html' %}
{% load static %}
{% block main %}
{% load ratings %}
{% load base_tags %}
{% load humanize %}

<!-- Page Header-->
<header class="masthead" style="background-image:url()"> {% comment %} ({% 'static' "images/back/back.jpg" %}); "  {% endcomment %}
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>نوس</h1>
                    <span class="subheading"> بلاگ جدید </span>
                </div>
            </div>
        </div>
    </div>
</header>
   <!-- Main Content-->
 <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            {% block header %}
            <h3 class="alert alert-primary text-center">{{category.title}}</h3>
            {% endblock%}

            <aside>
               {% popular_articles %}  
               {% hot_articles %}
            </aside>

          {% for post in object_list %}
            <!-- Post preview-->
            <div class="post-preview">
                <a href="{% url 'blog:detail' post.slug %}">
                    <h2 class="post-title">
                        {{post.title}}
                    {% if post.is_special %}
                        <span class="badge badge-danger" style="font-size: 14px;">ویژه</span>
                    {% endif %}
                </h2>
                    <h3 class="post-subtitle">{{post.description|striptags|truncatewords:30}}</h3>
                </a>
                <p class="post-meta">
                    نوشته شده 
                    <a href="{% url 'blog:author' post.author %}" >  {{post.author.get_full_name}}  </a>
                    <small>{{post.publish|naturaltime}}</small>
                   <div> <small>{% ratings post %}</small> </div>
                   <div> بازدید ها : {{post.hits.count}} </div>

                 {% endfor %}

                <div>
                    {% for cat in   page_obj.category.active %}
                    <a href="{% url 'blog:category' cat.slug %}">#{{cat.title}}</a>

                </div>
                
                </div>
                <hr>
                
                {% empty %}
                <p> متاسفانه موضوعی برای نمایش وجود ندارد. </p>
                

               {% endfor %}
            <!-- Pager-->

       <!-- Pager -->
       {% if is_paginated %}
       <div class="clearfix pager-botton">
         {% if page_obj.has_previous %}
           <a class="btn btn-primary float-right ml-3" href="{% block previous_page_url %}{% endblock %}">پست های جدید &rarr;</a>
         {% endif %}
         {% if page_obj.has_next %}
           <a class="btn btn-primary float-right" href="{% block next_page_url %}{% endblock %}">پست های قدیمی &larr;</a>
         {% endif %}
       </div>
     {% endif %}
   </div>
 </div>
</div>
{% endblock %}

 

templates/blog/search_list.html
{% extends 'blog/list.html' %}

{% block header %}
<h5 class="alert alert-primary "> جستجو : {{search}} </h5>
{% endblock%}

{% block previous_page_url %}
{% url 'blog:search1'  page_obj.previous_page_number %}?q={{search}}
{% endblock %}


{% block next_page_url %}
{% url 'blog:search1' page_obj.next_page_number %}?q={{search}}
{% endblock %}